/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>
int main(void)
{
    int32_t volatile *pRccClockReg =  (int32_t *)0x40023830;
    int32_t volatile *pGpioCModeReg = (int32_t *)0x40020800;
    int32_t volatile *pGpioCInReg =   (int32_t *)0x40020810;
    int32_t volatile *pGpioBModeReg = (int32_t *)0x40020400;
    int32_t volatile *pGpioBWrReg =   (int32_t *)0x40020414;


    *pRccClockReg |= 1 << 2;
    *pRccClockReg |= 1 << 1;
    *pGpioCModeReg &= ~(0x00000000);
    *pGpioBModeReg &= ~(0x00000280);
    *pGpioCModeReg |= 0<<24;
    *pGpioCModeReg |= 0<<25;
    *pGpioBModeReg |= 1<<14;
    *pGpioBModeReg |= 1<<28;


	for(;;){

		if((*pGpioCInReg >> 13) & 1){
		    	*pGpioBWrReg |= 1<<7;
		    	*pGpioBWrReg &= ~(1<<14);
		    }
		else{
				*pGpioBWrReg &= ~(1<<7);
				*pGpioBWrReg |= (1<<14);
		    }
	}
}
